apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-name
  namespace: namespace-name
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class-name
  nfs:
    server: intrenal-ip
    path: "intrenal-path-of-shareing-by-nfs-server-in-double-quotes"