apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-volume-claim-name
  namespace: namespace-name
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class-name
  resources:
    requests:
      storage: 1Gi